# Generated by Django 4.1.5 on 2023-04-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RoadFreight", "0002_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=50)),
                ("address", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
